name: crumpled_paper
oracle:
  ensemble: [gpt2-large, gpt2-medium]
  measurement_tokenizer: gpt2-large
alignment:
  algorithm: needleman_wunsch
  gap_penalty_bits: auto
metrics:
  tcm: true
  pcm: true
  delta_ll_bits: true
semantic_fidelity:
  enabled: true
  sbert_model: sentence-transformers/all-mpnet-base-v2
  span: auto
