name: efficiency
bpc:
  enabled: true
  compute_payload_bits: true
  compute_position_bits: true
bpt:
  enabled: true
amortised_bpc:
  enabled: true
  n_copies: [1, 10, 100, 1000, 10000, 100000, 1000000]
latency:
  enabled: true
  measure_decode_cpu: true
  measure_gpu_encode: true
  trials: 5
flops:
  enabled: true
  mode: auto
